### ISSUE TITLE
Levantamento de requisitos funcionais

### ISSUE THREAD

**Issue by clovisirie** [weslleyluiz/TransparencyPortal#1]
http://politicos.org.br/

**Comment by clovisirie** [comment]
- Pontuar políticos por projetos apresentados
- Ranquear políticos por pontuação
- Separar político por partido

**Comment by weslleyluiz** [comment]
Definir requisitos com base no portal 
http://transparencia.ppmc.com.br/

**Comment by weslleyluiz** [comment]
> * Pontuar políticos por projetos apresentados
> * Ranquear políticos por pontuação
> * Separar político por partido
> * Separar projetos por políticos
> * Separar projetos por status

**Comment by kateixeira** [comment]
Levantamento de requisitos:
RF001: O sistema deve armazenar informações vindo de servidores públicos e vereadores da câmara municipal de Mogi das Cruzes.
RF002: o sistema deve separar políticos por partido.
 RF003: O sistema deve possuir uma barra de pesquisa, contendo dados como, nome, cargo e salário dos vereadores.
RF004: O sistema deve interagir com o usuário comentando e avaliando outros comentários de forma que sua identidade seja privada.
RF005: O sistema deve possuir uma ferramenta que possibilite ver a comparação de informações e vereadores.
RF006: O sistema deve possuir uma ferramenta que possibilite ver o ranque dos vereadores.
USABILIDADE
RNF001:  O sistema deve conter apenas informações necessárias na tela de início e as informações secundárias devem vir em segundo plano através de (menus, barras, etc) com design minimalista.
RNF002: O sistema deve ser útil tanto para usuários experientes quanto para leigos.
RNF003: O sistema deva manter a padronização para facilitar o uso.
CONFIABILIDADE
RNF004: O sistema deve armazenar informações do banco de dados de f0orma segura
RNF005: o sistema deve ter disponibilidade a todo momento
MANUTENBILIDADE 
RNF006: o sistema deve ser de fácil manutenção.

**Comment by weslleyluiz** [comment]
> Levantamento de requisitos:
> RF001: O sistema deve armazenar informações vindo de servidores públicos e vereadores da câmara municipal de Mogi das Cruzes.
> RF002: o sistema deve separar políticos por partido.
> RF003: O sistema deve possuir uma barra de pesquisa, contendo dados como, nome, cargo e salário dos vereadores.
> RF004: O sistema deve interagir com o usuário comentando e avaliando outros comentários de forma que sua identidade seja privada.
> RF005: O sistema deve possuir uma ferramenta que possibilite ver a comparação de informações e vereadores.
> RF006: O sistema deve possuir uma ferramenta que possibilite ver o ranque dos vereadores.

Apenas esses são nesse ticket, vou mover os restantes para o outro ticket
