### ISSUE TITLE
Levantamento de regras de negócio

### ISSUE THREAD

**Issue by weslleyluiz** [weslleyluiz/TransparencyPortal#3]
Definir regras de negócio para o portal de transparência

**Comment by kateixeira** [comment]
As regras de negócio devem ser definidas a partir de uma política corporativa ou leis governamentais.
RN001: Em lei, o direito à privacidade está assegurado pelo inciso X, do artigo 5º da Constituição Federal, que prevê como invioláveis “(…) a intimidade, a vida privada, a honra e a imagem das pessoas, assegurado o direito a indenização pelo dano material ou moral decorrente de sua violação”.

**Comment by clovisirie** [comment]
RN002 – De acordo com a Lei complementar 131/2009 de 27 de Maio e à Lei 12527 o portal disponibilizará todas as informações de receitas e despesas do município.

RN003 – O acesso ao portal de transparência poderá ser feito por todos os usuários sem a necessidade de login e senha.
