### ISSUE TITLE
Regras de negócios

### ISSUE THREAD

**Issue by fabiohanada23** [weslleyluiz/TransparencyPortal#5]
Todas as regras de negocios

**Comment by fabiohanada23** [comment]
REGRAS DE NEGOCIOS

RN001 – O portal não haverá restrição de acesso, com exceção de alguns links direcionados aos funcionários da câmara.
RN002 – O portal irá separar todos os políticos por partido.
RN003 – O portal fornecerá informações dos servidores públicos e vereadores da câmara através do portal de transparência.
RN004 – O portal disponibilizara todos os conteúdos das sessões ordinárias ocorridas na câmara.
RN005 – O portal será responsável pela atualização do quadro de vereadores, servidores públicos de acordo com a sua admissão bem como o portal de transparência que será atualizado anualmente.
RN006 – O portal será cumpridor do ato divulgar noticias oficiais sobre os principais acontecimentos na cidade.

**Comment by weslleyluiz** [comment]
> RN02 – O acesso ao portal de transparência poderá ser feito por todos os usuários sem a necessidade de login e senha.

Movido para RNF
